services:
  - type: web
    name: homi-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: homi_backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: homi-postgres
          property: connectionString
      - key: JWT_EXPIRATION
        value: 3600
      - key: CORS_ALLOW_ORIGIN
        value: https://homi-by-isphers.vercel.app/
      - key: APP_SHARE_DIR
        value: /app/var/share
      - key: DEFAULT_URI
        value: https://homi-backend-ybjp.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: homi-postgres
    plan: free
    region: oregon
    databaseName: homi_db
    user: homi_user
