services:
  - type: web
    name: homi-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: homi_backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: homi-postgres
          property: connectionString
      - key: JWT_EXPIRATION
        value: "3600"
      - key: EMAIL_VERIFICATION_TOKEN_EXPIRATION
        value: "86400"
      - key: FRONTEND_URL
        value: https://lahatrar.github.io
      - key: MAILER_DSN
        value: smtp://lahatrariantsoaa%40gmail.com:wgtcglzraxomskfr@smtp.gmail.com:587?encryption=tls
      - key: MAILER_FROM
        value: lahatrariantsoaa@gmail.com
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
      - key: CORS_ALLOW_ORIGIN
        value: ^https://lahatrar\.github\.io$
      - key: APP_SHARE_DIR
        value: /app/var/share
      - key: DEFAULT_URI
        value: https://homi-backend-ybjp.onrender.com
      - key: TRUSTED_PROXIES
        value: 0.0.0.0/0
      - key: TRUSTED_HEADERS
        value: X_FORWARDED_FOR,X_FORWARDED_PROTO,X_FORWARDED_HOST,X_FORWARDED_PORT
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: homi-postgres
    plan: free
    region: oregon
    databaseName: homi_db
    user: homi_user
