services:
  - type: web
    name: homi-backend
    runtime: docker
    plan: free
    region: frankfurt
    rootDir: homi_backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: homi-postgres
          property: connectionString
      - key: JWT_EXPIRATION
        value: 3600
      - key: CORS_ALLOW_ORIGIN
        value: https://homi-by-isphers.vercel.app/
    preDeployCommand: cd homi_backend && php bin/console doctrine:migrations:migrate --no-interaction || true
    healthCheckPath: /api/tasks
    autoDeploy: true

databases:
  - name: homi-postgres
    plan: free
    databaseName: homi_db
    user: homi_user
