name: Déploiement GitHub Pages

on:
  push:
    branches:
      - main  # Branche qui déclenche le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Donne la permission de push au GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Racine contenant index.html
          destination_branch: gh-pages  # Branche de déploiement
